"""
Email service: Send analysis reports via email.
"""
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
FROM_NAME = os.environ.get("FROM_NAME", "AnZlyze")


def send_report_email(to_email: str, analysis_id: str, results_data: dict) -> bool:
    if not SMTP_USER or not SMTP_PASS:
        raise ValueError("SMTP credentials not configured. Set SMTP_USER and SMTP_PASS in .env")

    analysis = results_data.get("analysis", {})
    results = results_data.get("results", {})
    dist = results.get("sentiment_distribution", {})
    total = dist.get("total", 1)

    subject = f"AnZlyze Report: {analysis.get('filename', 'Analysis')}"

    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #6366f1, #a78bfa); padding: 24px; border-radius: 12px; text-align: center;">
            <h1 style="color: white; margin: 0;">AnZlyze Report</h1>
            <p style="color: rgba(255,255,255,0.8); margin-top: 8px;">Customer Review Analysis Results</p>
        </div>

        <div style="padding: 20px 0;">
            <h2 style="color: #334155;">Summary</h2>
            <table style="width: 100%; border-collapse: collapse; margin: 12px 0;">
                <tr><td style="padding: 8px; border-bottom: 1px solid #e2e8f0; font-weight: 600;">File</td><td style="padding: 8px; border-bottom: 1px solid #e2e8f0;">{analysis.get('filename', '')}</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #e2e8f0; font-weight: 600;">Reviews</td><td style="padding: 8px; border-bottom: 1px solid #e2e8f0;">{analysis.get('total_reviews', 0)}</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #e2e8f0; font-weight: 600;">Model</td><td style="padding: 8px; border-bottom: 1px solid #e2e8f0;">{results.get('best_model', '').replace('_', ' ').title()}</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #e2e8f0; font-weight: 600;">Accuracy</td><td style="padding: 8px; border-bottom: 1px solid #e2e8f0;">{results.get('best_accuracy', 0) * 100:.1f}%</td></tr>
            </table>

            <h2 style="color: #334155;">Sentiment Breakdown</h2>
            <div style="display: flex; gap: 12px; margin: 12px 0;">
                <div style="flex:1; text-align:center; padding: 16px; background: #f0fdf4; border-radius: 8px;">
                    <div style="font-size: 24px; font-weight: 700; color: #22c55e;">{dist.get('positive', 0)}</div>
                    <div style="font-size: 12px; color: #666;">Positive ({dist.get('positive', 0) / total * 100:.1f}%)</div>
                </div>
                <div style="flex:1; text-align:center; padding: 16px; background: #fef2f2; border-radius: 8px;">
                    <div style="font-size: 24px; font-weight: 700; color: #ef4444;">{dist.get('negative', 0)}</div>
                    <div style="font-size: 12px; color: #666;">Negative ({dist.get('negative', 0) / total * 100:.1f}%)</div>
                </div>
                <div style="flex:1; text-align:center; padding: 16px; background: #fefce8; border-radius: 8px;">
                    <div style="font-size: 24px; font-weight: 700; color: #f59e0b;">{dist.get('neutral', 0)}</div>
                    <div style="font-size: 12px; color: #666;">Neutral ({dist.get('neutral', 0) / total * 100:.1f}%)</div>
                </div>
            </div>
    """

    problems = results.get("problems", {}).get("problems", [])
    if problems:
        html_body += '<h2 style="color: #334155;">Top Problems</h2><ul style="padding-left: 20px;">'
        for p in problems[:5]:
            html_body += f'<li style="margin-bottom: 6px;"><strong>{p.get("category", "")}</strong> ({p.get("severity", "")}) - {p.get("frequency", 0)} mentions ({p.get("percentage", 0)}%)</li>'
        html_body += "</ul>"

    recs = results.get("recommendations", {}).get("recommendations", [])
    if recs:
        html_body += '<h2 style="color: #334155;">Recommendations</h2>'
        for r in recs[:5]:
            html_body += f'<div style="margin-bottom: 12px; padding: 12px; background: #f8fafc; border-left: 3px solid #6366f1; border-radius: 4px;">'
            html_body += f'<strong>[{r.get("priority", "").upper()}]</strong> {r.get("title", "")}<br>'
            html_body += f'<em style="color: #666;">{r.get("impact", "")}</em></div>'

    html_body += f"""
            <p style="color: #94a3b8; font-size: 12px; margin-top: 24px; text-align: center;">
                Generated by AnZlyze - Customer Review Intelligence Platform
            </p>
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"{FROM_NAME} <{SMTP_USER}>"
    msg["To"] = to_email
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.sendmail(SMTP_USER, [to_email], msg.as_string())

    return True
